---
- name: Isilon / PowerScale Gather Facts
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
          - dellemc.isilon

  vars_files:
          - vars/credsvault.yml

  tasks:
          - name: Gather facts on isilon
            dellemc_isilon_gatherfacts:
                    onefs_host: "{{ onefs_host }}"
                    port_no: "{{ isilon_port }}"
                    verify_ssl: "{{ verify_ssl }}"
                    api_user: "{{ api_user }}"
                    api_password: "{{ api_password }}"
                    gather_subset:
                            - attributes
            register: zresults

          - name: show me the value of a variable
            debug:
                    var: zresults
